### ISSUE TITLE
Failed to activate the particle-dev-profiles package

### ISSUE THREAD

**Issue by andyggraves** [spark/particle-dev-profiles#8]
![screen shot 2017-07-13 at 14 40 10](https://user-images.githubusercontent.com/17811978/28181869-c76d2880-6812-11e7-8068-e16b923198c4.png)

 just followed the update for one of the particle dev modules, now i am seeing the error.
Failed to activate the particle-dev-profiles package

**Comment by xavierdebriey** [comment]
Same issue ! 

Thanks !!

**Comment by andyggraves** [comment]
just installed a new update, now seeing this...

Uncaught TypeError: Cannot read property 'apiClient' of undefined

![screen shot 2017-07-14 at 09 36 09](https://user-images.githubusercontent.com/17811978/28201045-e7929d56-6877-11e7-9cc6-7e9c27ca2c60.png)

**Comment by suda** [comment]
You seem to be running standalone Particle Dev App that bundles all the packages already. Thus installing newer `particle-dev*` packages can brake it. I recommend removing them (so they're no longer visible in the **Community Packages** section). If you want to use the latest versions it's preferred to [install the in Atom](https://github.com/spark/particle-dev#github-atom)
